### ISSUE TITLE
Translations work in ribbon menu but do not work in other dialogs

### ISSUE THREAD

**Issue by DamienGombaultRecia** [aluxnimm/outlookcaldavsynchronizer#241] opened 2018-09-26 14:04 UTC
Hi.

I have a problem with the translations of the plugin.
I have configured the plugin in french language then restarted Outlook.
The CalDav Synchronizer ribbon menu is translated in french (screen1.png)
But others dialogs are in english (sync profiles, general options, etc.) (screen2.png).

I have deinstalled then reinstalled multiple times the plugin.
I tried another languages : same problem, the ribbon menu is translated, dialogs are not.

Windows version : Windows 10 Pro 1803 build 17134.285
Outlook Version : Office 365 Business 1808 build 10730.20102 C2R
CalDavSynchronizer Version : 3.2.1.0

How can I help you to debug this problem ?

Regards.

![screen1](https://user-images.githubusercontent.com/12713493/46085203-c5607e00-c1a5-11e8-9ae0-f926df5051a1.png)
![screen2](https://user-images.githubusercontent.com/12713493/46085205-c5607e00-c1a5-11e8-8b16-2bf344d090b4.png)

**Comment by aluxnimm** [comment] 2018-10-08 14:08
Very strange. Anything in the debug log.txt?

**Comment by aluxnimm** [comment] 2018-10-08 14:30
Is it correctly installed with the subfolder fr-FR in the install dir and the file CalDavSynchronizer.resources.dll ?

**Comment by DamienGombaultRecia** [comment] 2018-10-08 14:51
Plugin seems correctly installed.
![explorer_2018-10-08_16-50-48](https://user-images.githubusercontent.com/12713493/46616246-67735500-cb1a-11e8-8c27-db1ab4b850b5.png)

**Comment by DamienGombaultRecia** [comment] 2018-10-08 16:02
I have tried other languages, and I have the same problem.
The ribbon menu is translated in the selected language but the dialogs stay in English.

**Comment by aluxnimm** [comment] 2018-10-10 06:53
Did you also check the About dialog? Just to rule out that it has something to do with WPF windows?

**Comment by DamienGombaultRecia** [comment] 2018-10-10 07:51
The Profil sync dialog, General Options dialog, About dialog, Reports dialog and Status dialog are not translated.

**Comment by aluxnimm** [comment] 2018-11-30 11:19
Still can't reproduce your issues.

**Comment by aluxnimm** [comment] 2021-05-12 10:11
Localization issues should be fixed in new release 4.1.0.

**Closed by aluxnimm** 2021-05-12 10:11 UTC
