### ISSUE TITLE
Tentatively accepted meetings

### ISSUE THREAD

**Issue by marcelbrueckner** [aluxnimm/outlookcaldavsynchronizer#125] opened 2016-04-07 21:44 UTC
Hello,

I'm synchronizing an Exchange calendar one-way with a [Baïkal](https://github.com/fruux/Baikal) v0.2.7 CalDAV server.

Since version 2.0.0 (or one of the other last versions) my meeting's "invitation answer status" isn't synchronized and so new meetings appear as tentatively accepted (although I've accepted them on my Exchange calendar).

As you can see in my screenshot I'm using Mac OS X Calendar as CalDAV client.
The meeting on Monday appears as accepted but the meeting on Tuesday does not.
For both meetings I'm not the organizer. The meeting on Tuesday was updated by the organizer some time after a CalDAVSynchronizer update and all other meetings since then (see the meeting at Thursday 3PM) are tentatively accepted.

![calendar](https://cloud.githubusercontent.com/assets/3597890/14367573/05aeb340-fd19-11e5-8567-d15bbbf04484.jpg)

I don't want to accept the meeting invitation a second time on my Mac. They should have the same status as my Exchange calendar items. Are there any new configuration options I can use to restore the old behaviour?

Regards
Marcel

**Comment by aluxnimm** [comment] 2016-04-07 21:56
Can you test 2.0.1, we fixed a regression in checking own identity for exchange accounts which was introduced in 2.0.0.

**Comment by marcelbrueckner** [comment] 2016-04-08 11:35
I've updated to 2.0.1 and noticed the following:

* "old" meeting items won't be updated with the current status
* new meeting invitations will be synchronized as "tentatively accepted" (as I'm enabled the sync after change) and after I accept an invitation in Outlook a second item is created on my CalDAV server with the status "accepted" -> I now have 2 items for 1 meeting

**Comment by aluxnimm** [comment] 2016-04-08 11:45
Yes old meetings won't be changed unless you clear the sync cache, delete everything on the server and do a full sync Outlook->Server.

What happens if you disable sync changes immediately?
I guess the problem is that the invitation is synced immediately and when you accept it, Outlook creates a new Appointment with a new id and our sync logic can't detect that it is the same as the previous tentative item.

Does the email adress of the outlook profile match the email adress of the caldav server and are the attendees correct in both server items and the only difference that one of them is tentative?

**Comment by aluxnimm** [comment] 2016-04-08 12:09
I tried to reproduce this behaviour. In may case with sync changes immediately I also got 2 items on the server but with the next (manual or timed) sync run the first one(tentative) gets correctly deleted again, since it is not present in Outlook. What sync mode are you using Outlook->Server(Replicate) ?

**Comment by marcelbrueckner** [comment] 2016-04-08 12:45
Yes, I'm using Outlook -> Server (Replicate) synchronization mode.

And you are right. Looking at my calendar on Mac OS X the first one got deleted.
If I change a meeting item in Outlook which is tentatively accepted on my CalDAV server but accepted on Exchange, the acceptance status gets properly synced on the next run.
I'm ok with that as I'm not having so many meeting items with that "problem".

The e-mail addresses don't match on these two servers. The attendees are correct in both calendars.

Nevertheless, maybe you want to consider an additional option to fully sync all calendar items once a day or so (regardless of the item's "changed" status) :)

**Comment by aluxnimm** [comment] 2016-04-08 13:42
I will further investigate if we can detect the duplicate invite. Another possibility would be an option to exclude tentative items from sync changes immediately.

**Comment by aluxnimm** [comment] 2016-10-09 21:41
should be fixed in 2.7.0.

**Closed by aluxnimm** 2016-10-09 21:41 UTC
